# Generated by Django 5.2.6 on 2025-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pantry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='units',
            field=models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('mg', 'milligram'), ('lb', 'pound'), ('l', 'liter'), ('oz', 'ounce'), ('gr', 'grain'), ('bt', 'bottle'), ('bag', 'bag'), ('can', 'can')], default='kg', max_length=5),
        ),
    ]
