# Generated by Django 5.2.6 on 2025-09-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pantryitem_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pantryitem',
            old_name='units',
            new_name='unit',
        ),
    ]
