# Generated by Django 5.2.6 on 2025-09-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_units_pantryitem_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaselocation',
            options={'ordering': ['-name']},
        ),
    ]
