# Generated by Django 5.2.6 on 2025-09-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_purchaselocation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaselocation',
            options={'ordering': ['name']},
        ),
    ]
